#!/bin/bash
IS_RUNNING=$(docker-compose ps -q node-pku)
if [[ "$IS_RUNNING" != "" ]]; then
  docker-compose exec -T node-pku sh -c "node build/bin/pku.js $*"
else
  echo 'Контейнер ПКУ не создан. Попробуйте поднять его с помощью команды docker-compose up -d'
fi
