export const blobSelections = {
    rus: {
        id: 111,
        startSelection: 10,
        endSelection: 20,
        type: 'П.проблема',
        comment: '',
        explanation: '',
        correction: '',
        tag: '',
        group: 'meaning',
        subtype: '',
    },
    lit: {
        id: 111,
        startSelection: 10,
        endSelection: 20,
        type: 'С.опора',
        comment: '',
        explanation: '',
        correction: '',
        tag: '',
        group: 'meaning',
        subtype: '',
    },
    social: {
        id: 111,
        startSelection: 10,
        endSelection: 20,
        type: 'о.смысл',
        comment: '',
        explanation: '',
        correction: '',
        tag: '',
        group: 'error',
        subtype: '',
    },
    'rus-free': {
        id: 111,
        startSelection: 10,
        endSelection: 20,
        type: 'Г.слов',
        comment: '',
        explanation: '',
        correction: '',
        tag: '',
        group: 'error',
        subtype: '',
    },
    hist: {
        id: 111,
        startSelection: 10,
        endSelection: 20,
        type: 'И.личность',
        comment: '',
        explanation: '',
        correction: '',
        tag: '',
        group: 'error',
        subtype: '',
    },
    eng: {
        id: 111,
        startSelection: 10,
        endSelection: 20,
        type: 'А.стиль',
        comment: '',
        explanation: '',
        correction: '',
        tag: '',
        group: 'error',
        subtype: '',
    },
    'eng-free': {
        id: 111,
        startSelection: 10,
        endSelection: 20,
        type: 'А.стиль',
        comment: '',
        explanation: '',
        correction: '',
        tag: '',
        group: 'error',
        subtype: '',
    },
};
